YellowAfterlife/GMEdit

- .gitignore
- README.md
- package.json
- src/gml/Project.hx
This makes it easier to quickly compile and run from the command line. Also in the PR removes the "Loading..." text from the title bar when you first run the program.
> Add npm script aliases for compiling with Haxe and running with Electron

- bin/resources/app/formatter.js
- bin/resources/app/index.html
- src/ui/KeyboardShortcuts.hx
Currently bound to (CTRL || META) + F2, formats the ace editor window. Only performs operation if the ace editor is set to gml mode.
> Added potential GML formatting solution

- src/ui/MainMenu.hx
This is mostly so the MainMenu class can be change from plugins (ie add a new menu item)
> Made "menu" a static member of the "MainMenu" class

- bin/resources/app/index.html
- src/ui/GlobalSearch.hx
- src/yy/YySearcher.hx
As it was previously unimplemented
> Added global search support for room creation code

- bin/resources/app/api/shared/replace-v23.gml
- bin/resources/app/api/shared/types-v23.gml
Getting there slowly but surely
> 📃 Types 1/4th of fnames

- bin/resources/app/api/shared/replace-v23.gml
- bin/resources/app/api/shared/types-v23.gml
A little less than half to go! We're almost there.
> 🎉 1000 more fname definitions, fixes some mistakes

- bin/resources/app/api/shared/replace-v23.gml
- bin/resources/app/api/shared/types-v23.gml
3/4ths done!
Next pull request will be the last one.
> 🆔 Types about 800 more lines from fnames

- bin/resources/app/api/shared/replace-v23.gml
- bin/resources/app/api/shared/types-v23.gml
Purposefully left out all new sequence stuff. There's a lot of struct things going on there and I don't think we have the syntax to express it properly yet and if we do I don't feel comfortable enough with them to fill it out.
> 🎉 Final fname definitions

- src/ui/treeview/TreeViewElement.hx
- src/ui/treeview/TreeViewItemMenus.hx
Removes another popup, begging the question, why did I style it.
> 🌲 Resource tree inline creation

- src/gml/Project.hx
- src/gml/file/GmlFile.hx
- src/ui/ChromeTabs.hx
- src/ui/treeview/TreeViewItemMenus.hx
It's kinda hacky but I think this is as good as one can reasonably do it.
> 🔤→🖥️ Rename changes open window

- .gitignore
- .munit
- .vscode/editor.hxml
- .vscode/settings.json
- src/ace/extern/AceHighlight.hx
- src/electron/Electron.hx
- src/parsers/GmlReader.hx
- src/tools/ArrayMap.hx
- tests/test.hxml
- tests/unittest/TestMain.hx
- tests/unittest/TestRunnerCustom.hx
- tests/unittest/parsers/GmlReaderTest.hx
This is probably the most controversial pull request so far.
Not a lot of the code base can be easily tested at this point, but at least it compiles and runs now.
Tests can be ran with
`haxelib run munit test`
I'm honestly not super pleased with how this library turned out. The crashes and errors are presented from the JavaScript which is not nice at all.  But I do think it beats having nothing.
> 🧪 Initial testing

- src/parsers/linter/GmlLinterParser.hx
Don't ask what happened with the commits.
> 💲 Dollar properly treated when used as struct accessor

- bin/resources/app/css/popouts.css
- bin/resources/app/index.html
- bin/resources/app/themes/dark/dark.css
And prettier! (in my opinion)
Here's some examples:
Generally all white input fields have been removed. A lot of borders have been removed where applicable. There's new standard fields which should reduce redundant css going forward. Did I mention it looks gooder-er?
> 🌇 More consistently styled dark theme

- bin/resources/app/css/main.css
- bin/resources/app/themes/dark/dark.css
- src/editors/EditFont.hx
- src/editors/EditSound.hx
- src/file/FileKind.hx
- src/file/kind/yy/KYySound.hx
- src/parsers/GmlParseAPI.hx
- src/ui/treeview/TreeViewItemMenus.hx
- src/yy/YyManip.hx
- src/yy/YySound.hx
And some fixes for dark theme.
Pic:
Now that I've done the two most important resource editors, maybe I should do timelines next.
Or maybe paths. Certainly not sprites at least, can't imagine anyone using that.
> 🔊 Audio editor

- src/gml/file/GmlFileInMemory.hx
- src/parsers/linter/GmlLinter.hx
- tests/TestGMEditGMS23/scripts/v_cast_as/v_cast_as.gml
- tests/TestGMEditGMS23/scripts/v_truthy_instance/v_truthy_instance.gml
A birdie told me some of the casts we currently need may be unnecessary with some future updates to the linting. I thought it'd be neat if it warned you on if you still did it unnecessarily to help indicate when it's getting better.
Now, arguably this shouldn't be a warning. But as we don't really have something like "info" for VS I think this is the best we can do.
> 🎈🎈 Redundant cast warning

- bin/resources/app/api/shared/replace-v2.gml
Horrid crime against humanity.
> Fix layer sprite create typing ✏

- bin/resources/app/plugins/docs-tooltips/docs-tooltips.js
This also shows function syntax as it appears in the documentation, but preserves the generics added by gmedit
> Updates docs tooltips to work with new docs json format

- bin/resources/app/api/shared/replace-v23.gml
- bin/resources/app/api/shared/replace.gml
> Random API fixes

- bin/resources/app/ace/src-noconflict/ace.js
Back-port of https://github.com/ajaxorg/ace/pull/5717. Feels a lot nicer in my usage personally :)
> feat: smooth visual on dragging selection in Ace

- src/gml/type/GmlTypeCanCastTo.hx
> Cast T to any_fields_of<T>
