YellowAfterlife/GMEdit

.vscode/settings.json
This will force visual studio code to use tab characters instead of spaces when working in this directory.
=> Add vscode workspace setting to force tab character to be used

README.md
It seems preview 4 can't build GMEdit anymore. Compiling with preview 5 works.
=> Update link to newest version of Haxe 4

src/gml/Project.hx, src/plugins/PluginEvents.hx, src/plugins/PluginManager.hx
"ready" member was added as a workaround for plugin events being called too early, plugin events added for capturing projects being opened and closed
=> Added "ready" member to PluginManager and "projectOpen/projectClose" events

src/ui/FileDrag.hx
Running the packaged version of GMEdit on macOS will display an error message upon opening it because it detects the "-psn" argument and tries to interpret it as a file drop operation. This code just checks if the first 4 characters of the argument are not equal to `-psn` to decline it.
=> Fixes macOS builds falsely detecting ProcessSerialNumber

src/editors/EditSprite.hx
Added the ability to open a frame of a sprite externally by double-clicking it.
=> Sprite Frame Open Externally

src/parsers/GmlReader.hx, src/parsers/linter/GmlLinter.hx, src/parsers/linter/GmlLinterInit.hx, tests/unittest/TestRunnerCustom.hx
Also adds reading methods to GmlReader.
This makes tests not throw when the result is wrong, but no exception happened.
Should make it easier when you've made a lot of tests (and makes them easier to read) while retaining debuggability.
=> 🧪 Small test improvement

bin/resources/app/themes/gms2/gms2.css
Sets the primary color variable to the GMS2 color equivalent. Makes checkboxes, radios and selections a lot greener.
=> 🎮 Set primary color for gms2 theme

src/ace/AceGmlHighlight.hx
Removes the - from being captured by the number regex. Fixes -0xc0ffee not being captured as a number.
=> ➖ minus b gone

bin/resources/app/chrome-tabs/chrome-tabs.js
When chromeTabs is using simpleDrag, the tabsReorder event should be emitted.
=> emit 'tabsReorder' event when using multiline tabs

bin/resources/app/plugins/outline-view/outline-view.js
Fix for an obscure bug that only appears when outline-view display mode is set to "Only show the currently active document" and certain tab/file events are fired.
=> Fix outline-view plugin ignoring display mode

src/editors/sprite/EditSprite.hx
Add OpenDialog property 'openFile' on Import Images button, to allow the selection of files on macOS.
=> Fix for Sprite Editor not allowing the importing of images on macOS

bin/resources/app/plugins/docs-tooltips/config.json, bin/resources/app/plugins/docs-tooltips/docs-tooltips.js
Requesting to PR [this plugin](https://github.com/christopherwk210/gmedit-docs-tooltip) into master, to provide official GM documentation snippets inside of function tooltips.
Some concerns, in no particular order, that may or may not even need to be addressed:
- This feature relies on an internet connection to work, since it fetches an auto-generated JSON scrape of the official documentation, which can be found [here](https://raw.githubusercontent.com/christopherwk210/gm-bot/master/static/docs-index.json). This file is kept up to date by me for the purpose of powering [gm-bot](https://github.com/christopherwk210/gm-bot). If the file can't be fetched, then it fails silently with no indication to the user. Might be worth making a mention of that somewhere?
- This plugin uses the latest …
=> Added docs tooltip plugin

bin/resources/app/main.js, src/ace/AceCtxMenu.hx, src/electron/AppTools.hx
Resolves an issue where using 'Command+Q' would inadvertently quit GMEdit on MacOS, even when the editor wasn't in focus. The quit command, along with its shortcut, has now been added to the context menu, ensuring the app only closes when intended and preventing accidental exits while working in other applications.
=> Fix global quit shortcut by moving it to the context menu on MacOS.

src/parsers/GmlParseAPI.hx
Currently because of using `GmlTypeDef.simple` while parsing fields in built-in struct declarations (??structname) you can't hint them as complex types or collections. That may result, for example, in quirky warnings:
```js
var infos:room_info_instance[] = room_get_info(roomCheck, false, true, false, false, false).instances;
// shows "can't cast Array<room_info_instance> to Array<room_info_instance>" ???
```
Changing it to full `GmlTypeDef.parse` fixes the issue.
=> Complex parsing of built-in structs

bin/resources/app/api/shared/replace-v23.gml, bin/resources/app/api/shared/types-v23.gml, bin/resources/app/api/v23/extra.gml, src/gml/GmlAPILoader.hx
Currently, there're several issues with loading built-in structure declarations:
<details>
<summary><b>1. Struct fields with the same name are replaced with one declaration</b></summary>
\
`Expected:`
```js
??AnimCurveChannel
type?:animcurve_interpolation
// ...
??sprite_info
type?:int
// ...
??AudioEffect
type?:audio_effect_type
```
`Actual:`
```js
??AnimCurveChannel
type?:audio_effect_type
// ...
??sprite_info
type?:audio_effect_type
// ...
??AudioEffect
type?:audio_effect_type
```
</details>
<details>
<summary><b>2. Instance variables that have the same name as some struct field are replaced with it</b></summary>
\
`Expected:`
```js
visible@:bool
// ...
??Track
visible?:bool
```
`Actual:`
```js
visible?:bool
// ...
??Track
visible?:bool
```
</details>
<details>
<summary><b>3. Vice …
=> Fix API loading issues with built-in struct declarations

src/gml/funcdoc/GmlFuncDocParser.hx
This fixes this warning:
It seems that `showArgTypes` check is not needed there and it checks for it again on return anyways.
=> Fix trailing data warning for [optional] jsdoc arguments

src/parsers/seeker/GmlSeekerJSDocRegex.hx
Currently, something like
```js
arrayOfAnonStructs = [];    /// @is {Array<{ one:int, two:int, three:int }>}
```
is not possible as the regex stops on the first closed curly brace.
This fixes it.
Correct work is checked on:
```js
/// @is {type}
/// @is {type} comment
/// @is desc
```
=> Add ability to @is anonymous structs

README.md, bin/resources/app/main.js, bin/resources/app/package-lock.json, bin/resources/app/package.json, package-lock.json, package.json
Hello!
Not entirely sure why I devoted my hours today to this, but I've gone ahead and upgraded to the latest Electron version. Initially I was expecting this to be a pain given there'd be plenty of breaking changes between `v18` and `v33`, but all is working in my testing and I didn't find anything of note in Electron's own "Breaking Changes" listing between versions that seemed applicable to GMEdit's code.
I've tested the new compilation on Windows, MacOS and Linux all without issue.
I've also updated the documentation on how to setup GMEdit to contribute to it, and simplified the process a bit by using some pretty simple `npm` scripts.
Direct benefits of this upgrade mainly are not using an obsolete version of Electron. I've also noted a performance improvement in GMEdit's startup time …
=> Upgrade Electron to v33.2.0, plus nicer build experience

bin/resources/app/plugins/outline-view/outline-view.js, src/gml/file/GmlFile.hx, src/plugins/PluginEvents.hx, src/ui/treeview/TreeViewItemMenus.hx
Currently, the bundled `outline-view` plugin will not update the name of files in the tree when they are renamed in the project.
As this is a bundled plugin it has the luxury of being in sync with a specific GMEdit version, so I went ahead and exposed a new plugin event that fires whenever a file is renamed, which thus facilitates keeping in-sync with file name changes in the plugin.
Additionally I've moved the responsibility of refreshing a file's tab to happen within `file.rename` rather than being done manually at the callsite. This makes it a lot less of a pain to rename files from a plugin, since currently you're forced to mirror GMEdit's behaviour by manually editing the tab element, rather than renaming a file keeping this in line itself.
=> Fix `outline-view` not updating file names on renaming + Plugin API addition

src/plugins/PluginAPI.hx
Tiniest PR for something so very unimportant :P
https://github.com/HaxeFoundation/haxe/issues/7695 is closed, so this is no longer necessary.
=> fix: redundant `@:keep` annotation on plugin api

src/gml/Project.hx
Stops this pop-up when running directly with `npm run start`:
Just prevents attempting to load a file from `.`, since we can reasonably assume that one would not be trying to load GMEdit's directory as a project.
=> fix: don't show angry error box when in dev environment

bin/resources/app/plugins/docs-tooltips/docs-tooltips.js, bin/resources/app/plugins/image-viewer/image-viewer.js, bin/resources/app/plugins/ini-editor/ini-editor.js, bin/resources/app/plugins/outline-view/outline-view.js, src/Main.hx, src/file/FileKind.hx, src/file/kind/misc/KProjectProperties.hx, src/gml/Project.hx, src/plugins/PluginAPI.hx, src/plugins/PluginConfig.hx, src/plugins/PluginData.hx, src/plugins/PluginEvents.hx, src/plugins/PluginManager.hx, src/plugins/PluginState.hx, src/tools/ArrayTools.hx, src/tools/HtmlTools.hx, src/tools/Result.hx, src/ui/Preferences.hx, src/ui/preferences/PrefData.hx, src/ui/preferences/PrefMenu.hx, src/ui/preferences/PrefPlugins.hx, src/ui/project/ProjectProperties.hx
Plugins can now be disabled rather than being forced to remove them from the directory to prevent them from being initialised.
Disabled plugins have their groups minimised by default to show this visually.
If a plugin does not implement `cleanup`, the `reload` button will not display unless the plugin has not successfully loaded at all.
Additionally, plugins that do not implement `cleanup` have a tooltip on the `disable` button to indicate that toggling them requires a restart.
=> feat: enable and disable plugins at will!
